POST /persons
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
    "name": "Artem",
    "age": 35
}

###
GET /persons
Host: localhost:8080
Accept: application/json

###
GET /persons/0
Host: localhost:8080
Accept: application/json

###
PUT /persons/0
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
    "name": "Rustam"
}

###
DELETE /persons/0
Host: localhost:8080
Accept: application/json