POST /persons
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
    "name": "Artemh",
    "age": 35
}

###
GET /persons
Host: localhost:8080
Accept: application/json

###
GET /persons/0
Host: localhost:8080
Accept: application/json
