POST /persons
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
    "name": "Artem",
    "age": 35
}

###
GET /persons
Host: localhost:8080
Accept: application/json

###
GET /persons/2
Host: localhost:8080
Accept: application/json
